name: deploy-to-skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

      - name: "Deploy to Skynet"
         uses: SkynetLabs/deploy-to-skynet-action@v2.1.1
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
