# This is a basic workflow to help you get started with Actions
 - name: Skynet Deploy
  uses: SkynetLabs/deploy-to-skynet-action@v2.1.1
        with:
          upload-dir: public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
          registry-datakey: ${{ secrets.REGISTRY_DATAKEY || '' }}
